services:

  postgres:
    image: postgres:17
    container_name: game_postgres
    restart: always

    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: 1977
      POSTGRES_DB: game_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: game_pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: 1977

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: